name: 'Package version selector'
description: '...'
inputs:
  owner:
    description: "Repository owner or organization"
    required: true
  package:
    description: "Package name"
    required: true
  number-of-release-candidates-to-keep:
    description: "Number of versions to keep"
    required: true
  number-of-snapshots-to-keep:
    description: "Number of versions to keep"
    required: true
  number-of-feature-snapshots-to-keep:
    description: "Number of versions to keep"
    required: true
  github-token:
    description: "Github token (use secrets.GITHUB_TOKEN)"
    required: true
outputs:
  versionIds:
    description: 'Array of selected version ids'
runs:
  using: 'node12'
  main: 'select.js'
