name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: virtualidentityag/package-version-selector@update-for-registry
      id: version-selector
      with:
        owner: virtualidentityag
        github-token: ${{ secrets.github_token }}
        package: "infineon-myinfineon-service%2Finfineon-myinfineon-service"
        number-of-release-candidates-to-keep: 1
        number-of-snapshots-to-keep: 1
        number-of-feature-snapshots-to-keep: 1

    - run: echo ::set-env name=APPENDIX::${{ steps.version-selector.outputs.versionIds }}
    - run: echo ${{ env.APPENDIX }}
