name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: virtualidentityag/package-version-selector@update-for-registry
      id: version-selector
      with:
        owner: virtualidentityag
        github-token: ${{ secrets.VISUDOBOT_ORGSECRET_ALLREPOS_READWRITE }}
        package: "infineon-myinfineon-service/infineon-myinfineon-service"
        number-of-release-candidates-to-keep: 1
        number-of-snapshots-to-keep: 1
        number-of-feature-snapshots-to-keep: 1

    - run: echo "${{ steps.version-selector.outputs.versionIds }}" >> $GITHUB_ENV
    - run: echo "${{ env.APPENDIX }}"
